FROM microsoft/dotnet:2.1-aspnetcore-runtime-stretch-slim-arm32v7
ADD ./bin/Release/netcoreapp2.1/publish/ /app
ENV ASPNETCORE_URLS=http://*:${PORT}
WORKDIR /app
ENTRYPOINT [ "dotnet", "HelloWorldAspNetCore.dll"]
